// 2A1 Scratch 設定＋會走路的雪人 — 1~3 年級教學影片講稿資料（單一事實來源）
//
// 教案：2A1(1).pptx（40 頁）。年級預設 1~3（沿用 2A5 的低年級口語標準），要改年級請先講。
// 這份是「講稿草稿」，使用者確認之前不要開始組動畫（CLAUDE.md ①）。
//
// vis 對應 build-composition.mjs 的畫面組件（build 還沒寫，確認講稿後才寫）：
//   hook / demoVideo / title / goals / chapter       開場與章節卡
//   codebrainy / uiAreas / families / rightClick …   說明型畫面（用教案截圖＋circle()/arrow() 引導）
//   demoSteps（shots）/ demoClip（clip）              實作示範：靜態步驟圖，或教案附的螢幕錄影
//   quizAB / quizSpeed / reviewQ                     練習題（畫面標 A/B，旁白就唸 A/B）
//   codeBuild / codeFull / stageRun                  程式碼：積木逐塊疊上去、完整程式、舞台實跑
// src：該段用到的教案原圖（hyperframes-project/assets/2A1/raw/），box 等紅框座標等素材確認後再量。
//
// hold：該句講完後額外停留秒數（想一想／跟著做／抄寫）。
// tone／lead：可選的配音語氣，全片約 15~25% 的句子有，不要每句都加。
import { createHash } from 'node:crypto';

// tone／lead 是可選的配音語氣（見 SKILL.md「配音語氣」），沒寫就跟舊的雜湊一樣，既有音檔快取不會失效
export const voiceId = (t, ln = {}) => createHash('sha1')
  .update(speechText(t) + (ln.lead ? '|lead:' + ln.lead : '') + (ln.tone ? '|tone:' + ln.tone : ''))
  .digest('hex').slice(0, 10);

export const speechText = (t) =>
  t
    .replace(/[「」『』（）《》〈〉]/g, '')   // 引號會讓 TTS 在中間硬停一拍
    .replace(/＿+/g, '什麼')                  // 填空底線唸不出來，改成疑問詞
    .replace(/[—–]+/g, '，')                  // 破折號改成短停頓
    .replace(/[…⋯]+/g, '，')                  // 刪節號同上
    .replace(/，{2,}/g, '，')
    .replace(/[。，、]+$/, '')                 // 句尾句號會拖出一段長尾音
    .trim();

// 開場問題與結尾回扣必須是「同一句話」（teaching-rhythm 七之二-1），所以抽成常數
export const PAIN = '為什麼你畫好的雪人，怎麼點都不會動？';

export const SEGS = [
  // ═════════ 開場：痛點 → 成品 → 一句話自我介紹 → 學習目標 ═════════
  // 開場時間表：一句短問候（使用者要求，直接開講會怪）→ 痛點 → 成品 → 約 17 秒內學習目標；自我介紹併在目標後面那一句。
  // lead／tail 縮短是為了不讓段落之間的緩衝把學習目標擠到 20 秒以後。
  { id: 's01', title: '痛點提問（開場三秒）', part: '開場', vis: 'hook', tail: 0.15, lines: [
    { who: 'Cooper', action: 'greeting', text: '小朋友大家好！', tone: 'warm and cheerful' },
    { who: 'Cooper', action: 'thinking', text: PAIN, tone: 'curious and a little puzzled' },
    { who: 'Max', action: 'thinking', text: '我的雪人，好像在罰站耶。', tone: 'sheepish and a little embarrassed', lead: '<sigh>' },
  ]},
  { id: 's02', title: '先看成品（p.12／p.30 的雪人走路動畫）', part: '開場', vis: 'demoVideo', src: ['image20.gif'], lead: 0.15, tail: 0.15, lines: [
    { who: 'Cooper', action: 'guide_right', text: '下課以前，你會做出這個！' },
    { who: 'Max', action: 'eureka', text: '哇！雪人自己走起來了！', tone: 'excited and amazed', lead: '<gasp>' },
  ]},
  { id: 's04', title: '學習目標＋四個任務（p.2）', part: '開場', vis: 'goals', teach: true, src: ['image9.png'], lead: 0.15, lines: [
    { who: 'Cooper', action: 'guide_right', text: '看完這支影片，你會做出會走路的雪人，也會知道牠為什麼能走。', tone: 'warm and clear' },
    { who: 'Cora', action: 'greeting', text: '我是 Cora，聽起來好有趣！' },
    { who: 'Cooper', action: 'thinking', text: '想不想也做一隻這樣的雪人？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'greeting', text: '想！我是 Max，我想我想！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'greeting', text: '我是 Cooper 老師，我們先看看今天的四個任務。' },
    { who: 'Cooper', action: 'guide_left', text: '第一，認識 Scratch 和 CodeBrainy。' },
    { who: 'Max', action: 'talking', text: '第二，畫一隻我的雪人！' },
    { who: 'Cora', action: 'talking', text: '第三，來挑戰，看看觀念清不清楚。' },
    { who: 'Cooper', action: 'talking', text: '第四，最後有複習時間。' },
    { who: 'Cora', action: 'encourage', text: '四個任務，我們一個一個完成！' },
  ]},

  // ═════════ 第一章：認識 Scratch（p.3~10）═════════
  { id: 'c1', title: '章節卡：認識 Scratch', part: '第一部分：認識 Scratch 與 CodeBrainy', vis: 'chapter', chapter: true,
    chapNo: '1', chapTitle: '認識 Scratch', lines: [
    { who: 'Cooper', action: 'talking', text: '第一章，認識 Scratch。' },
  ]},
  { id: 's05', title: '認識 CodeBrainy（p.4）', vis: 'codebrainy', teach: true, src: ['image7.png'], lines: [
    { who: 'Cooper', action: 'thinking', text: '你上課和考試，都在哪個網站呢？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '我知道！是有可愛動物的那個網站！' },
    { who: 'Cooper', action: 'talking', text: '答對了，它叫做 CodeBrainy。' },
    { who: 'Cooper', action: 'guide_right', text: '上課和考試，都在這裡。' },
    { who: 'Cora', action: 'listening', text: '裡面還有遊樂場，可以練習寫程式。' },
    { who: 'Cooper', action: 'talking', text: '今天，我們就在遊樂場裡畫雪人。' },
  ]},
  // p.12 的登入畫面（image12）拍到真人帳號，不放進影片，從登入後的畫面開始
  { id: 'd01', title: '【實作】進入遊樂場（p.5~6）', vis: 'demoSteps', teach: true, caption: '跟著老師一起操作',
    shots: [
      { img: 'image13.png', on: '先按左邊的', box: null, arrow: 'right' },
      { img: 'image14.png', on: '再按這顆', box: null, arrow: 'right' },
      { img: 'image15.png', on: '進來了' },
    ],
    lines: [
      { who: 'Cooper', action: 'talking', text: '光用說的不夠，我們直接做一次。' },
      { who: 'Cooper', action: 'guide_left', text: '先按左邊的，遊樂場管理。' },
      { who: 'Cora', action: 'listening', text: '中間就會出現，加入遊樂場。' },
      { who: 'Cooper', action: 'guide_right', text: '再按這顆，直接進入遊樂場。' },
      { who: 'Max', action: 'thinking', text: '老師，我要打編號嗎？' },
      { who: 'Cooper', action: 'talking', text: '老師如果給你編號，才需要打。' },
      { who: 'Cooper', action: 'talking', text: '每堂課的編號都不一樣喔。今天直接進入就好。' },
      { who: 'Max', action: 'eureka', text: '哇，進來了！', tone: 'excited and amazed' },
      { who: 'Cooper', action: 'thinking', text: '你也打開遊樂場了嗎？沒有的話先暫停影片。', tone: 'curious and encouraging', hold: 4 },
    ]},
  { id: 's06', title: '看懂畫面：舞台、程式區（p.7 上）', vis: 'uiAreas', teach: true, src: ['image15.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '進到遊樂場，就是 Scratch 的畫面。' },
    { who: 'Cooper', action: 'thinking', text: '這麼多區塊，你猜哪一區是舞台？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '是不是角色站著的那一塊？' },
    { who: 'Cooper', action: 'talking', text: '沒錯！右上角那一大塊，就是舞台。' },
    { who: 'Cooper', action: 'guide_left', text: '左邊這一排，是程式家族。' },
    { who: 'Cora', action: 'listening', text: '中間大大的空白，是程式區。' },
    { who: 'Cooper', action: 'talking', text: '積木要拖到程式區，一塊一塊組起來。' },
    { who: 'Max', action: 'eureka', text: '像在地板上玩積木！', tone: 'excited and amazed' },
  ]},
  { id: 's07', title: '看懂畫面：角色與背景設定（p.7 下）', vis: 'uiAreas', teach: true, src: ['image15.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '舞台的下面，是角色設定。' },
    { who: 'Cora', action: 'listening', text: '這裡可以改角色的名字、位置和大小。' },
    { who: 'Cooper', action: 'guide_right', text: '再往下，是角色列表。' },
    { who: 'Max', action: 'talking', text: '所有的角色，都排在這裡！' },
    { who: 'Cooper', action: 'guide_right', text: '最右邊，是背景設定，可以換舞台的背景。' },
    { who: 'Cooper', action: 'thinking', text: '你的畫面上，也看到這幾區了嗎？', tone: 'curious and encouraging' },
    { who: 'Cora', action: 'talking', text: '我看到了，一區一區都找到了。' },
  ]},
  { id: 'q01', title: '【練習題 1】積木放哪一區', vis: 'quizAB', teach: true, quiz: true, question: '想排積木，要用哪一區？',
    opts: [{ k: 'A', t: '程式區' }, { k: 'B', t: '舞台' }], correct: 'A', lines: [
    { who: 'Cooper', action: 'thinking', text: '小考一下！' },
    { who: 'Cooper', action: 'guide_right', text: '想排積木，要用哪一區？' },
    { who: 'Cooper', action: 'talking', text: 'A 是中間的程式區，B 是右邊的舞台。', hold: 5 },
    { who: 'Cora', action: 'encourage', text: '我選 A！' },
    { who: 'Cooper', action: 'talking', text: '答對了！積木要排在程式區。' },
    { who: 'Cooper', action: 'talking', text: '舞台是用來看結果的地方。' },
  ]},
  { id: 'd02', title: '【實作】語言改成英文（p.8）', vis: 'demoSteps', teach: true, caption: '積木會變成英文',
    shots: [
      { img: 'image16.png', on: '先按左上角', box: null, arrow: 'right' },
      { img: 'image16.png', on: '往下找到', box: null, arrow: 'left' },
    ],
    lines: [
      { who: 'Cooper', action: 'talking', text: '接下來，我們把語言改成英文。' },
      { who: 'Max', action: 'thinking', text: '英文？我看不懂啦！', tone: 'sheepish and a little embarrassed' },
      { who: 'Cooper', action: 'talking', text: '這樣你的積木，才會跟老師的一模一樣。' },
      { who: 'Cooper', action: 'guide_left', text: '先按左上角的小齒輪，再選 Language。' },
      { who: 'Cora', action: 'listening', text: '裡面有好多國家的語言。' },
      { who: 'Cooper', action: 'guide_right', text: '往下找到 English，按一下。' },
      { who: 'Max', action: 'eureka', text: '真的變成英文了！', tone: 'excited and amazed' },
      { who: 'Cora', action: 'encourage', text: '別怕，積木上的字很短，看幾次就記住了。' },
      { who: 'Cooper', action: 'thinking', text: '你的畫面，也變成英文了嗎？', tone: 'curious and encouraging', hold: 4 },
    ]},
  { id: 's08', title: '存檔與命名（p.9）', vis: 'saveAs', teach: true, src: ['image17.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '做完專題，一定要記得存檔。' },
    { who: 'Cooper', action: 'guide_right', text: '按上面的 File，再按 Save as。' },
    { who: 'Cora', action: 'listening', text: '檔案就會存在你自己的電腦裡。' },
    { who: 'Cooper', action: 'thinking', text: '如果每個檔案，都叫「專題」，會怎樣？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '我會找不到哪一個是雪人！' },
    { who: 'Cooper', action: 'talking', text: '對！所以每個專題，都要取清楚的名字。' },
    { who: 'Cora', action: 'talking', text: '就像在書包上，貼名字貼紙。' },
    { who: 'Cooper', action: 'talking', text: '今天的專題，就取名叫「雪人」吧。' },
  ]},
  { id: 's09', title: '程式家族 1：動作、外觀、音效（p.10）', vis: 'families', teach: true, src: ['image18.png'], lines: [
    { who: 'Cooper', action: 'guide_left', text: '左邊這一排，叫做程式家族。' },
    { who: 'Cooper', action: 'talking', text: '每個家族，都有自己的顏色。' },
    { who: 'Cooper', action: 'guide_left', text: '藍色的，叫動作，英文是 Motion。' },
    { who: 'Cora', action: 'listening', text: '它讓角色走路、轉彎、跑到別的地方。' },
    { who: 'Max', action: 'thinking', text: '那紫色的呢？' },
    { who: 'Cooper', action: 'talking', text: '紫色是外觀，英文是 Looks。' },
    { who: 'Cooper', action: 'talking', text: '可以換造型，還能躲起來。' },
    { who: 'Cora', action: 'talking', text: '粉紅色是音效，英文是 Sound。' },
    { who: 'Max', action: 'eureka', text: '音效會讓角色發出聲音！', tone: 'excited and amazed' },
  ]},
  { id: 's10', title: '程式家族 2：事件、控制（p.10）', vis: 'families', teach: true, src: ['image18.png'], lines: [
    { who: 'Cooper', action: 'guide_left', text: '黃色是事件，英文是 Events。' },
    { who: 'Cooper', action: 'talking', text: '事件像門鈴，按一下，程式才會開始。' },
    { who: 'Cora', action: 'listening', text: '像是按下綠旗，程式就開始跑了。' },
    { who: 'Cooper', action: 'guide_left', text: '橘色是控制，英文是 Control。' },
    { who: 'Max', action: 'thinking', text: '控制是管什麼的呀？' },
    { who: 'Cooper', action: 'talking', text: '它像指揮官，叫大家一直重複做事。' },
    { who: 'Cora', action: 'talking', text: '今天要用的重複，就在橘色裡面。' },
  ]},
  { id: 's11', title: '程式家族 3：偵測、運算、變數、函式（p.10）', vis: 'families', teach: true, src: ['image18.png'], lines: [
    { who: 'Cooper', action: 'guide_left', text: '淺藍色是偵測，英文是 Sensing。' },
    { who: 'Cooper', action: 'talking', text: '偵測像眼睛，會看有沒有碰到東西。' },
    { who: 'Cora', action: 'talking', text: '綠色是運算，像一台計算機。' },
    { who: 'Max', action: 'talking', text: '橘紅色是變數，像一個收納箱。' },
    { who: 'Cooper', action: 'talking', text: '最後一個是函式，英文叫 My Blocks。' },
    { who: 'Cooper', action: 'talking', text: '可以自己做出，新的魔法積木。' },
    { who: 'Cooper', action: 'thinking', text: '九個家族，你覺得今天要全部學完嗎？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '要！我全部都要學！' },
    { who: 'Cooper', action: 'talking', text: '不用喔，今天只用四個家族。' },
    { who: 'Cora', action: 'listening', text: '動作、外觀、事件，還有控制。' },
    { who: 'Cooper', action: 'talking', text: '一次學一點，才不會亂掉。' },
  ]},
  { id: 'q02', title: '【練習題 2】去哪個家族找', vis: 'quizAB', teach: true, quiz: true, question: '想讓角色往前走，要去哪個家族找積木？',
    opts: [{ k: 'A', t: '動作 Motion' }, { k: 'B', t: '音效 Sound' }], correct: 'A', lines: [
    { who: 'Cooper', action: 'thinking', text: '再考一題！' },
    { who: 'Cooper', action: 'guide_right', text: '想讓角色往前走，要去哪個家族找積木？' },
    { who: 'Cooper', action: 'talking', text: 'A 是動作 Motion，B 是音效 Sound。', hold: 5 },
    { who: 'Max', action: 'eureka', text: '我選 A！走路就是動作！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '答對了，你抓到重點：走路是動作。' },
  ]},

  // ═════════ 第二章：角色和背景（p.11~17）═════════
  { id: 'c2', title: '章節卡：角色和背景', part: '第二部分：角色與背景', vis: 'chapter', chapter: true,
    chapNo: '2', chapTitle: '角色和背景', lines: [
    { who: 'Cooper', action: 'talking', text: '第二章，角色和背景。' },
  ]},
  { id: 's12', title: '當小小繪畫家（p.12）', vis: 'title2', teach: true, src: ['image19.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '這一章，我們來當小小繪畫家。' },
    { who: 'Cooper', action: 'guide_right', text: '先學怎麼新增角色，也學怎麼刪掉角色。' },
    { who: 'Cora', action: 'listening', text: '然後用繪畫工具，畫出自己的雪人。' },
    { who: 'Max', action: 'eureka', text: '我最喜歡畫畫了！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '畫好以後，還要讓牠動起來喔。' },
  ]},
  { id: 's13', title: '角色小檔案：名字與位置（p.13 上）', vis: 'spriteInfo', teach: true, src: ['image21.png'], lines: [
    { who: 'Cooper', action: 'guide_left', text: '舞台下面這一排，是角色的小檔案。' },
    { who: 'Cooper', action: 'guide_right', text: '最左邊，是角色的名字，現在叫 Sprite1。' },
    { who: 'Cora', action: 'listening', text: '名字可以自己改喔。' },
    { who: 'Cooper', action: 'guide_right', text: '後面的 x 和 y，是角色站的位置。' },
    { who: 'Max', action: 'thinking', text: '位置？要怎麼算呀？' },
    { who: 'Cooper', action: 'talking', text: 'x 是左右，y 是上下。' },
    { who: 'Cooper', action: 'talking', text: '就像教室座位，第幾排，第幾個。' },
    { who: 'Cora', action: 'listening', text: '數字改了，角色就跑到別的地方。' },
  ]},
  { id: 's14', title: '角色小檔案：顯示、大小、方向（p.13 下）', vis: 'spriteInfo', teach: true, src: ['image21.png'], lines: [
    { who: 'Cooper', action: 'guide_left', text: '再看下一排。' },
    { who: 'Cooper', action: 'talking', text: '眼睛打開，角色看得見。' },
    { who: 'Cooper', action: 'talking', text: '眼睛關起來，角色就躲起來了。' },
    { who: 'Max', action: 'eureka', text: '像在玩躲貓貓！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'guide_right', text: 'Size 是大小，一百，就是原來的大小。' },
    { who: 'Cooper', action: 'thinking', text: '想讓角色變大，數字要變大，還是變小？', tone: 'curious and encouraging' },
    { who: 'Cora', action: 'talking', text: '要變大！' },
    { who: 'Cooper', action: 'talking', text: '沒錯，數字越大，角色就越大。' },
    { who: 'Cooper', action: 'guide_right', text: 'Direction 是方向，九十，就是面向右邊。' },
    { who: 'Max', action: 'talking', text: '最下面的垃圾桶，是不是把角色丟掉？' },
    { who: 'Cooper', action: 'talking', text: '沒錯，按垃圾桶，角色就刪掉了。' },
  ]},
  { id: 's15', title: '新增角色的四個按鈕（p.14）', vis: 'addSprite', teach: true, src: ['image22.png', 'image23.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '想要新的角色，按右下角這顆按鈕。' },
    { who: 'Cooper', action: 'talking', text: '按一下，上面會跑出四個小按鈕。' },
    { who: 'Cora', action: 'listening', text: '最上面是上傳，可以放自己的圖片。' },
    { who: 'Max', action: 'eureka', text: '閃閃發亮的是隨機，讓電腦幫你挑！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '畫筆是繪製，自己畫一個角色。' },
    { who: 'Cora', action: 'talking', text: '放大鏡是選擇，從角色庫裡面找。' },
    { who: 'Cooper', action: 'thinking', text: '想畫自己的雪人，要按哪一個？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '畫筆！' },
    { who: 'Cooper', action: 'talking', text: '沒錯，等一下就用畫筆來畫雪人。' },
  ]},
  { id: 's16', title: '換背景（p.15）', vis: 'addBackdrop', teach: true, src: ['image24.png', 'image25.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '背景也是一樣的做法。' },
    { who: 'Cooper', action: 'talking', text: '按右下角，背景的按鈕。' },
    { who: 'Cora', action: 'listening', text: '也有上傳、隨機、繪製和選擇。' },
    { who: 'Cooper', action: 'talking', text: '角色是演員，背景是布景。' },
    { who: 'Cooper', action: 'thinking', text: '演員和布景，哪一個會走來走去？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '演員！布景站著不動！' },
    { who: 'Cooper', action: 'talking', text: '對，所以會動的程式，要寫在角色身上。' },
  ]},
  { id: 's17', title: '右鍵的三個功能（p.16）', vis: 'rightClick', teach: true, src: ['image26.png', 'image27.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '對著角色按滑鼠右鍵，會跑出三個功能。' },
    { who: 'Cooper', action: 'guide_right', text: '第一個，duplicate，是複製。' },
    { who: 'Max', action: 'thinking', text: '複製？變出兩隻一模一樣的嗎？' },
    { who: 'Cooper', action: 'talking', text: '對，就像影印機。' },
    { who: 'Cooper', action: 'guide_right', text: '第二個，export，是把角色存成檔案。' },
    { who: 'Cora', action: 'listening', text: '存成檔案，就可以送給朋友。' },
    { who: 'Cooper', action: 'guide_right', text: '第三個，delete，是刪除。' },
    { who: 'Cooper', action: 'thinking', text: '想多一隻一模一樣的角色，要選哪一個？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'eureka', text: '複製，duplicate！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '沒錯，右鍵再按 duplicate，就會多一隻。' },
  ]},
  { id: 's18', title: '造型就是動畫的每一格（p.17）', vis: 'costumes', teach: true, src: ['image28.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '再告訴你們一個秘密：角色的造型。' },
    { who: 'Cooper', action: 'guide_right', text: '點上面的 Costumes，就是造型。' },
    { who: 'Cooper', action: 'talking', text: '你看，這隻貓咪有兩個造型。' },
    { who: 'Max', action: 'thinking', text: '兩個一樣的貓咪，有什麼用？' },
    { who: 'Cooper', action: 'talking', text: '不一樣喔，兩個的姿勢不一樣。' },
    { who: 'Cooper', action: 'talking', text: '輪流換造型，看起來就像在走路！' },
    { who: 'Cooper', action: 'thinking', text: '想一想，翻書動畫是不是也這樣？', tone: 'curious and encouraging' },
    { who: 'Cora', action: 'talking', text: '一頁一頁快快翻，圖就動起來了！' },
    { who: 'Cooper', action: 'talking', text: '沒錯，造型就是動畫的每一格。' },
  ]},
  { id: 'q03', title: '【練習題 3】要幾個造型', vis: 'quizAB', teach: true, quiz: true, question: '想讓貓咪看起來像在走路，需要幾個造型？',
    opts: [{ k: 'A', t: '一個造型' }, { k: 'B', t: '兩個以上' }], correct: 'B', lines: [
    { who: 'Cooper', action: 'thinking', text: '小考一下！' },
    { who: 'Cooper', action: 'guide_right', text: '想讓貓咪看起來像在走路，需要幾個造型？' },
    { who: 'Cooper', action: 'talking', text: 'A 是一個造型，B 是兩個以上。', hold: 5 },
    { who: 'Cora', action: 'encourage', text: '我選 B！輪流換，才像在走路。' },
    { who: 'Cooper', action: 'talking', text: '答對了！造型要輪流換，才會動起來。' },
  ]},

  // ═════════ 第三章：畫一隻雪人（p.18~24）═════════
  { id: 'c3', title: '章節卡：畫一隻雪人', part: '第三部分：畫雪人', vis: 'chapter', chapter: true,
    chapNo: '3', chapTitle: '畫一隻雪人', lines: [
    { who: 'Cooper', action: 'talking', text: '第三章，畫一隻雪人。' },
  ]},
  { id: 's19', title: '打開畫布（p.18）', vis: 'openPaint', teach: true, src: ['image22.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '現在，我們要畫雪人了！' },
    { who: 'Cooper', action: 'guide_right', text: '按角色按鈕裡面的畫筆。' },
    { who: 'Cora', action: 'listening', text: '畫布就打開了。' },
    { who: 'Max', action: 'eureka', text: '一張空白的畫紙！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '除了選現成的角色，也可以畫自己的人物。' },
    { who: 'Cooper', action: 'thinking', text: '如果可以畫，你最想畫什麼角色？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '我想畫恐龍！' },
    { who: 'Cooper', action: 'talking', text: '好呀，今天先畫雪人，回家再畫恐龍。' },
  ]},
  { id: 's20', title: '畫布上方：顏色與粗細（p.19 左）', vis: 'paintTop', teach: true, src: ['image29.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '畫布上面，有一排按鈕。' },
    { who: 'Cooper', action: 'guide_left', text: '最重要的，是 Fill 和 Outline。' },
    { who: 'Cooper', action: 'talking', text: 'Fill 是填滿，就是圖形裡面的顏色。' },
    { who: 'Cooper', action: 'talking', text: 'Outline 是外框，就是圖形的邊線。' },
    { who: 'Cora', action: 'listening', text: '旁邊的數字，是邊線的粗細。' },
    { who: 'Max', action: 'thinking', text: '數字越大，線就越粗嗎？' },
    { who: 'Cooper', action: 'talking', text: '沒錯，想要粗一點，就把數字改大。' },
  ]},
  { id: 's21', title: '畫布上方：複製、群組、圖層、翻轉（p.19 右）', vis: 'paintTop', teach: true, src: ['image29.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '中間有 Copy 和 Paste，就是複製、貼上。' },
    { who: 'Cooper', action: 'talking', text: 'Group 是把好幾個東西，綁在一起。' },
    { who: 'Cora', action: 'listening', text: '這樣就可以一起搬走！' },
    { who: 'Cooper', action: 'talking', text: 'Forward，是往前移一層。' },
    { who: 'Cooper', action: 'talking', text: 'Backward，是往後移一層。' },
    { who: 'Max', action: 'thinking', text: '像疊紙張，看誰壓在誰上面？' },
    { who: 'Cooper', action: 'talking', text: '最後 Flip，是翻轉，左右或上下翻過來。' },
    { who: 'Cooper', action: 'thinking', text: '如果帽子被頭蓋住了，該怎麼辦？', tone: 'curious and encouraging' },
    { who: 'Cora', action: 'talking', text: '把帽子往前移一層！' },
    { who: 'Cooper', action: 'talking', text: '對，按 Front，帽子就跑到最上面。' },
  ]},
  { id: 's22', title: '畫布旁邊的工具（p.20）', vis: 'paintTools', teach: true, src: ['image30.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '畫布旁邊，有一排工具。' },
    { who: 'Cooper', action: 'talking', text: '今天會用到五個。' },
    { who: 'Cooper', action: 'guide_right', text: '第一個是選取，點一下，就能把東西搬走。' },
    { who: 'Cora', action: 'talking', text: '第二個是畫圓，畫頭和身體。' },
    { who: 'Max', action: 'talking', text: '第三個是畫線，畫雪人的手！' },
    { who: 'Cooper', action: 'talking', text: '第四個是畫矩形，畫帽子。' },
    { who: 'Cooper', action: 'talking', text: '第五個是塑型，可以把方形，改成尖尖的。' },
    { who: 'Cora', action: 'listening', text: '另外還有畫筆、橡皮擦、文字和油漆桶。' },
  ]},
  { id: 'q04', title: '【練習題 4】該選哪個工具', vis: 'quizAB', teach: true, quiz: true, question: '想畫雪人圓圓的身體，要選哪個工具？',
    opts: [{ k: 'A', t: '畫圓工具', img: 'image33.png' }, { k: 'B', t: '畫線工具', img: 'image36.png' }], correct: 'A', lines: [
    { who: 'Cooper', action: 'thinking', text: '換你想一想！' },
    { who: 'Cooper', action: 'guide_right', text: '想畫雪人圓圓的身體，要選哪個工具？' },
    { who: 'Cooper', action: 'talking', text: 'A 是畫圓，B 是畫線。', hold: 5 },
    { who: 'Max', action: 'eureka', text: '我選 A！圓圓的就要用圓！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '答對了，畫線是用來畫雪人的手。' },
  ]},
  { id: 's23', title: '看看要畫成什麼樣子（p.21）', vis: 'snowmanGoal', teach: true, src: ['image31.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '看，這就是我們要畫的雪人。' },
    { who: 'Cooper', action: 'talking', text: '有頭、有身體，還有兩隻手。' },
    { who: 'Cora', action: 'listening', text: '還有黑黑的眼睛，和一頂小帽子。' },
    { who: 'Cooper', action: 'talking', text: '我們分成三步來畫。' },
    { who: 'Cooper', action: 'talking', text: '第一步畫頭，第二步畫身體和手。' },
    { who: 'Max', action: 'thinking', text: '那第三步呢？' },
    { who: 'Cooper', action: 'talking', text: '第三步，畫帽子和眼睛。' },
    { who: 'Max', action: 'eureka', text: '只有三步，好簡單！', tone: 'excited and amazed' },
  ]},
  // clip：教案附的螢幕錄影（media1~3.mp4，有聲音，要靜音）。實際取用的起訖秒數等看過影格再定
  { id: 'd03', title: '【實作】第一步：畫頭（p.22）', vis: 'demoClip', teach: true, caption: '先畫一個小圓當頭',
    clip: { src: 'media1.mp4', from: null, to: null }, tools: ['image33.png', 'image34.png'],
    lines: [
      { who: 'Cooper', action: 'talking', text: '第一步，畫雪人的頭。' },
      { who: 'Cooper', action: 'guide_right', text: '先選畫圓工具。' },
      { who: 'Cooper', action: 'talking', text: '在畫布上，按住滑鼠，拉出一個小圓。' },
      { who: 'Cora', action: 'listening', text: '放開滑鼠，圓圈就畫好了！' },
      { who: 'Cooper', action: 'talking', text: '圓圈的位置不對，就換選取工具。' },
      { who: 'Cooper', action: 'talking', text: '點一下圓，就能拖去別的地方。' },
      { who: 'Max', action: 'eureka', text: '圓圈可以搬來搬去耶！', tone: 'excited and amazed' },
      { who: 'Cooper', action: 'thinking', text: '你也畫好雪人的頭了嗎？', tone: 'curious and encouraging', hold: 4 },
    ]},
  { id: 's24', title: '畫錯了怎麼辦（錯誤正常化）', vis: 'undo', teach: true, src: ['image32.png'], lines: [
    { who: 'Max', action: 'thinking', text: '糟糕，我的圓畫歪了，變成蛋了。', tone: 'sheepish and a little embarrassed', lead: '<sigh>' },
    { who: 'Cooper', action: 'talking', text: '沒關係，畫錯很正常，老師也常常畫錯。', tone: 'gentle and reassuring' },
    { who: 'Cooper', action: 'talking', text: '拉的時候，橫的和直的不一樣長，圓就變成蛋了。' },
    { who: 'Cooper', action: 'guide_left', text: '按上面的回上一步箭頭，就退回去了。' },
    { who: 'Cora', action: 'listening', text: '也可以按 Delete，刪掉重畫一次。' },
    { who: 'Cooper', action: 'talking', text: '寫程式的工程師也一樣，錯了就修，修好再繼續。', tone: 'warm and proud' },
  ]},
  { id: 'd04', title: '【實作】第二步：畫身體和手（p.23）', vis: 'demoClip', teach: true, caption: '大圓當身體，兩條線當手',
    clip: { src: 'media2.mp4', from: null, to: null }, tools: ['image34.png', 'image33.png', 'image36.png'],
    lines: [
      { who: 'Cooper', action: 'talking', text: '第二步，畫身體和手。' },
      { who: 'Cooper', action: 'talking', text: '一樣用畫圓工具，在頭的下面拉出一個大圓。' },
      { who: 'Max', action: 'thinking', text: '大圓的裡面是空的，看得到後面耶。' },
      { who: 'Cooper', action: 'guide_left', text: '把 Fill 改成白色，身體就變成實心的了。' },
      { who: 'Max', action: 'eureka', text: '哇，真的不透明了！', tone: 'excited and amazed' },
      { who: 'Cooper', action: 'guide_right', text: '再選畫線工具，畫兩隻手。' },
      { who: 'Cora', action: 'listening', text: '一條往左上，一條往右上。' },
      { who: 'Cooper', action: 'thinking', text: '你也做出雪人的身體和手了嗎？', tone: 'curious and encouraging', hold: 4 },
    ]},
  { id: 'd05', title: '【實作】第三步：畫帽子和眼睛（p.24）', vis: 'demoClip', teach: true, caption: '黑色的眼睛，黃色的帽子',
    clip: { src: 'media3.mp4', from: null, to: null }, tools: ['image33.png', 'image38.png', 'image37.png'],
    lines: [
      { who: 'Cooper', action: 'talking', text: '最後一步，畫眼睛和帽子。' },
      { who: 'Cooper', action: 'guide_right', text: '眼睛用畫圓工具，先畫一個小圓。' },
      { who: 'Cooper', action: 'guide_left', text: '把 Fill 改成黑色，眼睛就黑黑的。' },
      { who: 'Cora', action: 'listening', text: '再畫一個，就有兩隻眼睛了，好像真的在看著我們！' },
      { who: 'Cooper', action: 'talking', text: '帽子先用畫矩形工具，畫一個小方塊。' },
      { who: 'Cooper', action: 'guide_left', text: '這次把 Fill 改成黃色。' },
      { who: 'Cooper', action: 'guide_right', text: '再換成塑型工具，把方塊拉成尖尖的帽子。' },
      { who: 'Max', action: 'eureka', text: '哇！雪人戴上帽子了！', tone: 'excited and amazed' },
      { who: 'Cooper', action: 'thinking', text: '你的雪人，也戴好帽子了嗎？', tone: 'curious and encouraging', hold: 4 },
    ]},
  { id: 's25', title: '【變化題】只改 Fill 會怎樣', vis: 'fillOutline', teach: true, lines: [
    { who: 'Cooper', action: 'thinking', text: '猜猜看！如果只把 Fill 改成藍色，會變怎樣？', tone: 'curious and encouraging', hold: 4 },
    { who: 'Max', action: 'thinking', text: '整個圓圈的線，都變成藍色？' },
    { who: 'Cooper', action: 'talking', text: '不是喔，Fill 管的是裡面的顏色。' },
    { who: 'Cooper', action: 'talking', text: '變成藍色的是圓圈的裡面，外框還是黑色。' },
    { who: 'Cora', action: 'talking', text: '那想改外框的顏色，就要改 Outline。' },
    { who: 'Cooper', action: 'talking', text: 'Cora 分得很清楚：一個管裡面，一個管邊線。', tone: 'warm and proud' },
    { who: 'Max', action: 'eureka', text: '那我可以畫一個藍色的雪人！', tone: 'excited and amazed' },
  ]},

  // ═════════ 第四章：讓雪人動起來（p.25~30）═════════
  { id: 'c4', title: '章節卡：讓雪人動起來', part: '第四部分：迴圈與程式', vis: 'chapter', chapter: true,
    chapNo: '4', chapTitle: '讓雪人動起來', lines: [
    { who: 'Cooper', action: 'talking', text: '第四章，讓雪人動起來。' },
  ]},
  { id: 's26', title: '什麼是迴圈（p.25）', vis: 'loopIntro', teach: true, src: ['image40.png'], lines: [
    { who: 'Cooper', action: 'thinking', text: '你每天早上起床，都做哪些事情？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '起床、吃早餐、刷牙！' },
    { who: 'Cooper', action: 'thinking', text: '那星期二早上呢？也一樣嗎？' },
    { who: 'Cora', action: 'talking', text: '一樣！每天都是這三件事。' },
    { who: 'Cooper', action: 'talking', text: '一樣的事情，一直重複做，就叫迴圈。' },
    { who: 'Cooper', action: 'guide_right', text: '電腦也有迴圈，可以一直做一樣的事。' },
    { who: 'Max', action: 'eureka', text: '那雪人的走路，也可以重複嗎？', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '對！一直向前走，一直換造型，一直重複。' },
  ]},
  { id: 's27', title: '有限迴圈和無限迴圈', vis: 'loopTypes', teach: true, lines: [
    { who: 'Cooper', action: 'talking', text: '迴圈有兩種。' },
    { who: 'Cooper', action: 'guide_left', text: '第一種，重複十次就停，叫有限迴圈。' },
    { who: 'Cooper', action: 'guide_right', text: '第二種，永遠不會停，叫無限迴圈。' },
    { who: 'Cora', action: 'listening', text: '像操場一直跑，不下課就不停。' },
    { who: 'Max', action: 'thinking', text: '那雪人要用哪一種呢？' },
    { who: 'Cooper', action: 'talking', text: '雪人要一直走，所以用無限迴圈。' },
    { who: 'Cora', action: 'talking', text: '它的名字叫 forever，意思就是永遠。' },
  ]},
  { id: 's28', title: '旋轉方式 1：left-right（p.26）', vis: 'rotation', teach: true, src: ['image41.png', 'image42.png', 'image43.png'], lines: [
    { who: 'Cooper', action: 'thinking', text: '雪人往左走的時候，臉要朝哪裡？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '朝左邊啊！' },
    { who: 'Cooper', action: 'talking', text: '沒錯，這時候就要設定旋轉方式。' },
    { who: 'Cooper', action: 'guide_right', text: '這一塊，叫 set rotation style。' },
    { who: 'Max', action: 'thinking', text: '名字好長喔，我記不住。' },
    { who: 'Cooper', action: 'talking', text: '不用背，意思就是：設定旋轉的方式。' },
    { who: 'Cooper', action: 'talking', text: '旁邊有三個選項，我們一個一個看。' },
    { who: 'Cooper', action: 'guide_right', text: '第一個，left-right，是左右。' },
    { who: 'Cora', action: 'listening', text: '往右走，臉朝右。往左走，臉朝左。' },
    { who: 'Max', action: 'eureka', text: '像照鏡子，左右翻過來！', tone: 'excited and amazed' },
  ]},
  { id: 's29', title: '旋轉方式 2：don\'t rotate（p.27）', vis: 'rotation', teach: true, src: ['image44.png', 'image42.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '第二個，don\'t rotate，是不要轉。' },
    { who: 'Cooper', action: 'talking', text: '不管往哪裡走，臉都朝同一邊。' },
    { who: 'Max', action: 'thinking', text: '那往左走，不就變成倒退走了？' },
    { who: 'Cooper', action: 'talking', text: '對！就像倒著走路。' },
    { who: 'Cora', action: 'listening', text: '臉一直朝著前面，不會轉過去。' },
  ]},
  { id: 's30', title: '【變化題】旋轉方式 3：all around（p.28）', vis: 'rotation', teach: true, src: ['image46.png', 'image45.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '第三個，all around，是整個轉一圈。' },
    { who: 'Cooper', action: 'thinking', text: '猜猜看，選了 all around，往左走會怎樣？', tone: 'curious and encouraging', hold: 4 },
    { who: 'Max', action: 'thinking', text: '會在原地轉圈圈嗎？' },
    { who: 'Cooper', action: 'talking', text: '不是轉圈圈喔。看看畫面。' },
    { who: 'Cora', action: 'listening', text: '啊！頭朝下了，變成倒著走！', lead: '<gasp>' },
    { who: 'Cooper', action: 'talking', text: '對，整張圖跟著方向轉，往左走就會頭下腳上。' },
    { who: 'Cooper', action: 'talking', text: '所以雪人要選 left-right，才會站著走。' },
    { who: 'Cora', action: 'encourage', text: '這樣往左往右，都是站著走。' },
  ]},
  { id: 's31', title: '積木 1：move 10 steps（p.29）', vis: 'blockIntro', teach: true, blockKey: 'move10', src: ['image51.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '現在，來認識雪人要用的積木。' },
    { who: 'Cooper', action: 'guide_right', text: '第一塊，move 十 steps，意思是移動十步。' },
    { who: 'Cora', action: 'listening', text: '每跑一次，雪人就往前走十步。' },
    { who: 'Max', action: 'thinking', text: '十步是多遠呀？' },
    { who: 'Cooper', action: 'talking', text: '舞台很大，十步只是一小段。' },
    { who: 'Cooper', action: 'thinking', text: '想一想，這塊積木在哪個家族？', tone: 'curious and encouraging' },
    { who: 'Cora', action: 'talking', text: '藍色的動作家族！' },
    { who: 'Cooper', action: 'talking', text: '沒錯，因為走路是動作。' },
  ]},
  { id: 's32', title: '積木 2：next costume（p.29）', vis: 'blockIntro', teach: true, blockKey: 'nextCostume', lines: [
    { who: 'Cooper', action: 'guide_right', text: '第二塊，next costume，是下一個造型。' },
    { who: 'Cooper', action: 'talking', text: '它是紫色的，在外觀家族。' },
    { who: 'Max', action: 'eureka', text: '就是翻到下一頁！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '對，翻一下，角色就換一個造型。' },
    { who: 'Cora', action: 'listening', text: '貓咪就是這樣，換著換著，就像在走路。' },
  ]},
  { id: 's33', title: '積木 3：if on edge, bounce（p.29）', vis: 'blockIntro', teach: true, blockKey: 'bounce', src: ['image56.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '第三塊，if on edge, bounce。' },
    { who: 'Cooper', action: 'talking', text: '意思是：碰到邊邊，就彈回來。' },
    { who: 'Max', action: 'thinking', text: '雪人走到舞台邊邊，要怎麼辦？' },
    { who: 'Cooper', action: 'talking', text: '這塊積木，會幫雪人轉身。' },
    { who: 'Cora', action: 'listening', text: '就像撞到牆壁，彈回來。' },
    { who: 'Cooper', action: 'talking', text: '它也是藍色的，在動作家族。' },
  ]},
  { id: 's34', title: '積木 4：forever（p.29）', vis: 'blockIntro', teach: true, blockKey: 'forever', src: ['image49.png'], lines: [
    { who: 'Cooper', action: 'guide_right', text: '第四塊，forever，意思是永遠。' },
    { who: 'Cooper', action: 'talking', text: '它是橘色的，在控制家族。' },
    { who: 'Cooper', action: 'guide_right', text: '它像一張大嘴巴，把積木包起來。' },
    { who: 'Cora', action: 'listening', text: '被包起來的積木，會一直重複做。' },
    { who: 'Max', action: 'eureka', text: '一直走，一直換造型，一直轉身！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '對，這就是無限迴圈。' },
  ]},
  { id: 's35', title: '積木 5：when flag clicked', vis: 'blockIntro', teach: true, blockKey: 'whenFlag', lines: [
    { who: 'Cooper', action: 'talking', text: '最後，要有人說「開始」。' },
    { who: 'Cooper', action: 'guide_right', text: '這塊叫 when 綠旗 clicked。' },
    { who: 'Cooper', action: 'talking', text: '意思是：按下綠旗，程式就開始。' },
    { who: 'Cora', action: 'listening', text: '它是黃色的，在事件家族。' },
    { who: 'Max', action: 'eureka', text: '就像按下門鈴，才會響！', tone: 'excited and amazed' },
  ]},
  { id: 's36', title: '★ 雪人的完整程式（p.29 截圖）', vis: 'codeFull', teach: true, src: ['image47.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '我們把全部的積木，排在一起。' },
    { who: 'Cooper', action: 'guide_right', text: '最上面，是 when 綠旗 clicked。' },
    { who: 'Cooper', action: 'guide_right', text: '下面接 set rotation style。' },
    { who: 'Max', action: 'thinking', text: '後面那個字，要選哪一個？' },
    { who: 'Cooper', action: 'talking', text: '選 left-right，雪人才會左右轉身。' },
    { who: 'Cora', action: 'listening', text: '它在 forever 外面，因為只要設定一次。' },
    { who: 'Cooper', action: 'guide_right', text: '再放 forever，把三塊積木包在裡面。' },
    { who: 'Max', action: 'talking', text: '裡面有 move 十 steps。' },
    { who: 'Cora', action: 'talking', text: '還有 next costume。' },
    { who: 'Cooper', action: 'talking', text: '最後是 if on edge, bounce。' },
    { who: 'Cooper', action: 'talking', text: '暫停影片，照著螢幕排排看。', hold: 6 },
  ]},
  { id: 'd06', title: '【實作】按綠旗，讓雪人走起來', vis: 'demoSteps', teach: true, caption: '沒有動，先檢查積木有沒有卡好',
    shots: [
      { img: 'image15.png', on: '按下舞台上面的', box: null, arrow: 'left', crop: 'flag' },
      { img: 'image15.png', on: '紅色的圓點', box: null, arrow: 'left', crop: 'stop' },
    ],
    lines: [
      { who: 'Cooper', action: 'talking', text: '都排好了，按下舞台上面的綠旗！' },
      { who: 'Max', action: 'eureka', text: '哇，雪人走起來了！', tone: 'excited and amazed' },
      { who: 'Cora', action: 'encourage', text: '走到邊邊，真的彈回來了！' },
      { who: 'Cooper', action: 'guide_right', text: '想讓雪人停下來，就按旁邊紅色的圓點。' },
      { who: 'Cooper', action: 'thinking', text: '你的雪人也走起來了嗎？', tone: 'curious and encouraging', hold: 5 },
      { who: 'Max', action: 'thinking', text: '我的雪人還是站著不動耶……', tone: 'sheepish and a little embarrassed' },
      { who: 'Cooper', action: 'talking', text: '沒關係，這個狀況很多人都會遇到。', tone: 'gentle and reassuring' },
      { who: 'Cooper', action: 'talking', text: '先檢查積木有沒有卡在一起，沒卡好，程式就不會跑。' },
      { who: 'Cora', action: 'listening', text: '把積木靠近一點，放開手，看到它黏住，就卡好了。' },
    ]},
  { id: 's37', title: '做完記得存檔', vis: 'saveAs', teach: true, src: ['image17.png'], lines: [
    { who: 'Cooper', action: 'talking', text: '雪人走起來了，記得馬上存檔。' },
    { who: 'Cooper', action: 'guide_right', text: '按 File，再按 Save as。' },
    { who: 'Cora', action: 'listening', text: '名字要取得清楚，就叫雪人。' },
    { who: 'Max', action: 'talking', text: '這樣下次打開，我就找得到了！' },
    { who: 'Cooper', action: 'thinking', text: '你的雪人，也存好檔案了嗎？', tone: 'curious and encouraging', hold: 4 },
  ]},
  { id: 's38', title: '成果展示（p.30）', vis: 'demoVideo', src: ['image20.gif'], lines: [
    { who: 'Cooper', action: 'talking', text: '全部完成，我們來看看成果！' },
    { who: 'Max', action: 'eureka', text: '雪人自己走起來了！', tone: 'excited and amazed' },
    { who: 'Cora', action: 'encourage', text: '我們沒有推牠，是程式叫牠走的。' },
    { who: 'Cooper', action: 'talking', text: '你從畫圖，到排積木，每一步都是自己完成的。', tone: 'warm and proud' },
    { who: 'Cooper', action: 'thinking', text: '舉手給老師看看，你的雪人也會走了嗎？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '我的會走了！我要回家表演給大家看！' },
  ]},

  // ═════════ 第五章：挑戰時間（p.31~37）═════════
  { id: 'c5', title: '章節卡：挑戰時間', part: '第五部分：學生挑戰', vis: 'chapter', chapter: true,
    chapNo: '5', chapTitle: '挑戰時間', lines: [
    { who: 'Cooper', action: 'talking', text: '第五章，挑戰時間。' },
  ]},
  { id: 'q05', title: '【挑戰 1】有限還是無限（p.32~33）', vis: 'quizAB', teach: true, quiz: true, question: '這個程式是有限還是無限迴圈？', src: ['image49.png'],
    opts: [{ k: 'A', t: '有限' }, { k: 'B', t: '無限' }], correct: 'B', lines: [
    { who: 'Cooper', action: 'thinking', text: '第一題！請問這個程式，是有限還是無限迴圈？' },
    { who: 'Cooper', action: 'talking', text: 'A 是有限，B 是無限。', hold: 5 },
    { who: 'Cora', action: 'encourage', text: '我選 B！' },
    { who: 'Cooper', action: 'talking', text: '答對了！forever 是永遠，所以是無限。' },
    { who: 'Cooper', action: 'talking', text: '你抓到重點：forever 沒有數字，所以不會停。', tone: 'warm and proud' },
  ]},
  { id: 'q06', title: '【挑戰 2】沒有這塊會怎樣（p.34~35）', vis: 'quizAB', teach: true, quiz: true, question: '如果沒有這塊積木，雪人會怎樣？', src: ['image50.png'],
    opts: [{ k: 'A', t: '不會怎樣' }, { k: 'B', t: '角色會跑出舞台' }], correct: 'B', lines: [
    { who: 'Cooper', action: 'thinking', text: '第二題！如果沒有這塊積木，雪人會怎樣？' },
    { who: 'Cooper', action: 'talking', text: 'A 是不會怎樣，B 是角色會跑出舞台。', hold: 5 },
    { who: 'Max', action: 'eureka', text: '我選 B！牠會走出去，不見了！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'talking', text: '答對了！沒有人幫牠轉身，牠就一直走出舞台。' },
    { who: 'Cora', action: 'talking', text: '這塊積木，就像舞台的牆壁！' },
  ]},
  { id: 'q07', title: '【挑戰 3】誰走比較快（p.36~37）', vis: 'quizSpeed', teach: true, quiz: true, question: '這三個雪人，誰會走比較快？', src: ['image51.png', 'image52.png', 'image53.png'],
    opts: [{ k: 'A', t: 'move 10 steps', n: 10 }, { k: 'B', t: 'move 40 steps', n: 40 }, { k: 'C', t: 'move 90 steps', n: 90 }], correct: 'C', lines: [
    { who: 'Cooper', action: 'thinking', text: '第三題！這三個雪人，誰會走比較快？' },
    { who: 'Cooper', action: 'talking', text: 'A 是十步，B 是四十步，C 是九十步。', hold: 6 },
    { who: 'Max', action: 'thinking', text: '我選 A，因為十比較簡單。' },
    { who: 'Cora', action: 'talking', text: '我選 C！數字越大，一次走越遠。' },
    { who: 'Cooper', action: 'talking', text: '答對了，是 C，一次走九十步。' },
    { who: 'Cooper', action: 'talking', text: '走得快不快，不是看簡單，是看一次走幾步。' },
    { who: 'Max', action: 'eureka', text: '原來是這樣，我懂了！', tone: 'excited and amazed' },
  ]},

  // ═════════ 第六章：複習時間（p.38~40）═════════
  { id: 'c6', title: '章節卡：複習時間', part: '第六部分：複習與結尾', vis: 'chapter', chapter: true,
    chapNo: '6', chapTitle: '複習時間', lines: [
    { who: 'Cooper', action: 'talking', text: '第六章，複習時間到囉！' },
  ]},
  { id: 'r01', title: '【複習 1】這塊積木做什麼？（p.39）', vis: 'reviewQ', teach: true, quiz: true,
    blockKey: 'setRotation', answer: '設定旋轉方式，選左右', qLine: 1, aLine: 3, lines: [
    { who: 'Cooper', action: 'talking', text: '先來複習今天學的積木。' },
    { who: 'Cooper', action: 'thinking', text: '請問這個程式，是用來做什麼的呢？', tone: 'curious and encouraging', hold: 5 },
    { who: 'Max', action: 'eureka', text: '我知道！是設定雪人怎麼轉身！', tone: 'excited and amazed' },
    { who: 'Cooper', action: 'guide_right', text: '對，沒錯！這個程式，是用來設定旋轉方式，我們選左右。' },
  ]},
  { id: 'r02', title: '【複習 2】這塊積木做什麼？（p.39~40）', vis: 'reviewQ', teach: true, quiz: true,
    blockKey: 'bounce', answer: '碰到邊緣就彈回來', qLine: 0, aLine: 2, lines: [
    { who: 'Cooper', action: 'thinking', text: '那這一塊呢？它是用來做什麼的？', tone: 'curious and encouraging', hold: 5 },
    { who: 'Cora', action: 'talking', text: '雪人走到邊緣，就彈回來！' },
    { who: 'Cooper', action: 'guide_right', text: '對，沒錯！如果角色碰到邊緣，就彈回來。' },
  ]},
  { id: 'r03', title: '【複習 3】這塊積木做什麼？', vis: 'reviewQ', teach: true, quiz: true,
    blockKey: 'forever', answer: '讓裡面的積木一直重複', qLine: 0, aLine: 2, lines: [
    { who: 'Cooper', action: 'thinking', text: '再看一個，這個程式是做什麼用的？', tone: 'curious and encouraging', hold: 5 },
    { who: 'Max', action: 'talking', text: '讓裡面的積木，一直重複做！' },
    { who: 'Cooper', action: 'guide_right', text: '對，沒錯！forever 會讓裡面的積木，一直重複。' },
  ]},
  { id: 'r04', title: '【複習 4】這塊積木做什麼？', vis: 'reviewQ', teach: true, quiz: true,
    blockKey: 'nextCostume', answer: '換成下一個造型', qLine: 0, aLine: 2, lines: [
    { who: 'Cooper', action: 'thinking', text: '最後一個，這塊你認得嗎？', tone: 'curious and encouraging', hold: 5 },
    { who: 'Cora', action: 'encourage', text: '是換成下一個造型！' },
    { who: 'Cooper', action: 'guide_right', text: '對，沒錯！這個程式，是用來換成下一個造型。' },
    { who: 'Cooper', action: 'talking', text: '四題都答對，你們今天真的有認真學。', tone: 'warm and proud' },
  ]},
  // 回扣開場：必須用「同一句話」再問一次，由學生角色自己答出來
  { id: 's39', title: '回扣開場的問題', vis: 'callback', teach: true, lines: [
    { who: 'Cooper', action: 'thinking', text: `還記得一開始的問題嗎？${PAIN}`, tone: 'curious and encouraging', hold: 4 },
    { who: 'Max', action: 'eureka', text: '因為只畫圖還不夠，要放 move 積木，雪人才會走！', tone: 'excited and amazed' },
    { who: 'Cora', action: 'talking', text: '還要用 forever，讓牠一直走下去！' },
    { who: 'Cooper', action: 'talking', text: '答對了，就是第四章，排積木的那一步。', tone: 'warm and proud' },
    { who: 'Cooper', action: 'talking', text: '畫圖是做出雪人，積木是叫雪人動起來。' },
  ]},
  { id: 's40', title: '今天學了什麼', vis: 'summary', teach: true, lines: [
    { who: 'Cooper', action: 'talking', text: '我們來回想一下，今天學的東西。' },
    { who: 'Cooper', action: 'guide_right', text: '第一個：認識 Scratch，還有九個程式家族。' },
    { who: 'Cora', action: 'talking', text: '第二個：用畫筆，畫出自己的雪人。' },
    { who: 'Max', action: 'talking', text: '第三個：用 forever 和 move，讓雪人走起來！' },
    { who: 'Cooper', action: 'thinking', text: '這三件事，你記得幾件呢？', tone: 'curious and encouraging' },
    { who: 'Cora', action: 'encourage', text: '我三件都記得！' },
    { who: 'Cooper', action: 'talking', text: '你們都記得，因為你們有動手做。' },
  ]},
  { id: 's41', title: '下課囉', vis: 'ending', lines: [
    { who: 'Cooper', action: 'talking', text: '今天的課就到這裡。' },
    { who: 'Cooper', action: 'talking', text: '回家記得，做一隻會走路的雪人，給爸爸媽媽看。' },
    { who: 'Cooper', action: 'thinking', text: '今天你最喜歡哪個部分呢？', tone: 'curious and encouraging' },
    { who: 'Max', action: 'talking', text: '我最喜歡，看雪人自己走起來！' },
    { who: 'Max', action: 'goodbye', text: '大家下次見！' },
    { who: 'Cora', action: 'goodbye', text: '拜拜！' },
    { who: 'Cooper', action: 'goodbye', text: '我們下次見，拜拜！' },
  ]},
];
